version: '3'

services:

  mysql-dev:
    image: mysql:8.0.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: dsrdb
    ports:
      - 3308:3306

  backend2:
    build: ./backend
    ports:
      - 8888:8888
    volumes:
      - ./backend:/var/www/backend


